name: Boringgggg

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Maven manually
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build jar
        run: |
          mvn clean package -DskipTests

      - name: Show generated files
        run: |
          ls -R target

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: java-build-output
          path: |
            target/*.jar
            target/*.war
            target/*.zip
          if-no-files-found: warn
